alter session set deferred_segment_creation=false;
ALTER SESSION SET NLS_DATE_FORMAT = 'yyyy-mm-dd';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'yyyy-mm-dd hh24:mi:ss';


DROP TABLE DIVEMESSAGE;
DROP TABLE MEM;
DROP TABLE DIVE;
DROP TABLE WEATHER_AREA;
DROP TABLE WEATHER_LOCAL;

DROP SEQUENCE SEQ_WT_LOCAL_NO;
DROP SEQUENCE SEQ_WEATHER_AREA_NO;
DROP SEQUENCE SEQ_DIVE_NO;
DROP SEQUENCE SEQ_MEM_NO;
DROP SEQUENCE SEQ_DIVEMESSAGEL_NO;

CREATE TABLE WEATHER_LOCAL (
    WT_LOCAL VARCHAR2(7) NOT NULL,
    WT_TEMP VARCHAR2(10),
    WT_WATERTEMP VARCHAR2(10),
    WT_RAINRATE VARCHAR2(10),
    WT_WAVEHEIGHT VARCHAR2(10),
    WT_SUNRISE TIMESTAMP,
    WT_SUNDOWN TIMESTAMP,
    WT_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP Not Null,
    CONSTRAINT WEATHER_LOCAL PRIMARY KEY (WT_LOCAL)
);

CREATE SEQUENCE SEQ_WT_LOCAL_NO
START WITH 1
INCREMENT BY 1
NOMAXVALUE 
NOCYCLE
NOCACHE;


CREATE TABLE WEATHER_AREA (
    WEATHER_AREA_NO VARCHAR2(7) PRIMARY KEY NOT NULL,
    WT_LOCAL VARCHAR2(7) NOT NULL,
    CONSTRAINT WEATHER_AREA_TO_WEATHER_LOCAL FOREIGN KEY (WT_LOCAL) REFERENCES WEATHER_LOCAL(WT_LOCAL)
);

CREATE SEQUENCE SEQ_WEATHER_AREA_NO
START WITH 1
INCREMENT BY 1
NOMAXVALUE 
NOCYCLE
NOCACHE;

CREATE TABLE DIVE (
    DIVE_NO VARCHAR2(7) PRIMARY KEY NOT NULL,
    WEATHER_AREA_NO VARCHAR2(7) NOT NULL,
    DIVE_NAME VARCHAR2(50) NOT NULL,
    DIVE_DES VARCHAR2(200),
    DIVE_IMG BLOB,
    DIVE_STATUS NUMBER(7),
    DIVE_LAT VARCHAR2(20) NOT NULL,
    DIVE_LANG VARCHAR2(20) NOT NULL,

    CONSTRAINT DIVE_TO_WEATHER_AREA FOREIGN KEY (WEATHER_AREA_NO) REFERENCES WEATHER_AREA(WEATHER_AREA_NO)
);

CREATE SEQUENCE SEQ_DIVE_NO
START WITH 1
INCREMENT BY 1
NOMAXVALUE 
NOCYCLE
NOCACHE;

CREATE TABLE MEM(
MEM_NO             VARCHAR2(7) PRIMARY KEY NOT NULL,
MEM_NAME           VARCHAR2(20),
MEM_ID             VARCHAR2(20) NOT NULL,
MEM_PSW            VARCHAR2(20) NOT NULL,
MEM_GENERAL_GEN    NUMBER(1),
MEM_GENERAL_BD     DATE,
MEM_TEL            NUMBER(10),
MEM_EMAIL          VARCHAR2(50),
MEM_ADD            VARCHAR2(100),
MEM_IMG            BLOB,
MEM_PER            NUMBER(1) NOT NULL,
MEM_TYPE           NUMBER(1) NOT NULL,
MEM_STORE_BUSINESS BLOB,
MEM_STORE_OWNER    VARCHAR2(20),
MEM_STORE_TAXID    VARCHAR2(8)
);

CREATE SEQUENCE SEQ_MEM_NO
START WITH 1
INCREMENT BY 1
NOMAXVALUE 
NOCYCLE
NOCACHE;

CREATE TABLE DIVEMESSAGE (
    DIVMEG_NO VARCHAR2(7) PRIMARY KEY NOT NULL,
    DIVE_NO VARCHAR2(7) NOT NULL,
    MEM_NO VARCHAR2(7) NOT NULL,
    DIVMEG_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP Not Null,
    DIVMEG_NOTE VARCHAR2(200) NOT NULL,

    CONSTRAINT DIVEMESSAGE_TO_DIVE FOREIGN KEY (DIVE_NO) REFERENCES DIVE(DIVE_NO),
    CONSTRAINT DIVEMESSAGE_TO_MEMBER FOREIGN KEY (MEM_NO) REFERENCES MEMBER(MEM_NO)
);

CREATE SEQUENCE SEQ_DIVEMESSAGEL_NO
START WITH 1
INCREMENT BY 1
NOMAXVALUE 
NOCYCLE
NOCACHE;

//WEATHER_LOCAL假資料
INSERT INTO WEATHER_LOCAL (WT_LOCAL , WT_TEMP , WT_WATERTEMP , WT_RAINRATE , WT_WAVEHEIGHT , WT_SUNRISE , WT_SUNDOWN , WT_TIME  )
VALUES ('WL'||LPAD(to_char(SEQ_WT_LOCAL_NO.NEXTVAL), 5, '0'),'21' ,'24', '80',
'110','2019-08-11 05:24:31', '2019-08-11 18:24:31', CURRENT_TIMESTAMP);

INSERT INTO WEATHER_LOCAL (WT_LOCAL , WT_TEMP , WT_WATERTEMP , WT_RAINRATE , WT_WAVEHEIGHT , WT_SUNRISE , WT_SUNDOWN , WT_TIME  )
VALUES ('WL'||LPAD(to_char(SEQ_WT_LOCAL_NO.NEXTVAL), 5, '0'),'24' ,'23', '85',
'120','2019-08-12 05:24:31', '2019-08-12 18:24:31', CURRENT_TIMESTAMP);

INSERT INTO WEATHER_LOCAL (WT_LOCAL , WT_TEMP , WT_WATERTEMP , WT_RAINRATE , WT_WAVEHEIGHT , WT_SUNRISE , WT_SUNDOWN , WT_TIME  )
VALUES ('WL'||LPAD(to_char(SEQ_WT_LOCAL_NO.NEXTVAL), 5, '0'),'21' ,'22', '75',
'130','2019-08-13 05:24:31', '2019-08-13 18:24:31', CURRENT_TIMESTAMP);

INSERT INTO WEATHER_LOCAL (WT_LOCAL , WT_TEMP , WT_WATERTEMP , WT_RAINRATE , WT_WAVEHEIGHT , WT_SUNRISE , WT_SUNDOWN , WT_TIME  )
VALUES ('WL'||LPAD(to_char(SEQ_WT_LOCAL_NO.NEXTVAL), 5, '0'),'25' ,'24', '60',
'140','2019-08-14 05:24:31', '2019-08-14 18:24:31', CURRENT_TIMESTAMP);

INSERT INTO WEATHER_LOCAL (WT_LOCAL , WT_TEMP , WT_WATERTEMP , WT_RAINRATE , WT_WAVEHEIGHT , WT_SUNRISE , WT_SUNDOWN , WT_TIME  )
VALUES ('WL'||LPAD(to_char(SEQ_WT_LOCAL_NO.NEXTVAL), 5, '0'),'26' ,'24', '90',
'150','2019-08-15 05:24:31', '2019-08-15 18:24:31', CURRENT_TIMESTAMP);


//WEATHER_AREA假資料
INSERT INTO WEATHER_AREA (WEATHER_AREA_NO , WT_LOCAL )
VALUES ('WA'||LPAD(to_char(SEQ_WEATHER_AREA_NO.NEXTVAL), 5, '0'),'WL00001');

INSERT INTO WEATHER_AREA (WEATHER_AREA_NO , WT_LOCAL )
VALUES ('WA'||LPAD(to_char(SEQ_WEATHER_AREA_NO.NEXTVAL), 5, '0'),'WL00002');

INSERT INTO WEATHER_AREA (WEATHER_AREA_NO , WT_LOCAL )
VALUES ('WA'||LPAD(to_char(SEQ_WEATHER_AREA_NO.NEXTVAL), 5, '0'),'WL00003');

INSERT INTO WEATHER_AREA (WEATHER_AREA_NO , WT_LOCAL )
VALUES ('WA'||LPAD(to_char(SEQ_WEATHER_AREA_NO.NEXTVAL), 5, '0'),'WL00004');

INSERT INTO WEATHER_AREA (WEATHER_AREA_NO , WT_LOCAL )
VALUES ('WA'||LPAD(to_char(SEQ_WEATHER_AREA_NO.NEXTVAL), 5, '0'),'WL00005');


//DIVE假資料
INSERT INTO DIVE (DIVE_NO, WEATHER_AREA_NO, DIVE_NAME, DIVE_DES, DIVE_IMG, DIVE_STATUS, DIVE_LAT, DIVE_LANG )
VALUES ('D'||LPAD(to_char(SEQ_DIVE_NO.NEXTVAL), 6, '0'),'WA00001' ,'DiveName1', 'Beautifull Place',
null,'0', '125.0215648', '25.5646846');

INSERT INTO DIVE (DIVE_NO, WEATHER_AREA_NO, DIVE_NAME, DIVE_DES, DIVE_IMG, DIVE_STATUS, DIVE_LAT, DIVE_LANG )
VALUES ('D'||LPAD(to_char(SEQ_DIVE_NO.NEXTVAL), 6, '0'),'WA00002' ,'DiveName2', 'Beautifull Place',
null,'0', '125.0215648', '25.5646846');

INSERT INTO DIVE (DIVE_NO, WEATHER_AREA_NO, DIVE_NAME, DIVE_DES, DIVE_IMG, DIVE_STATUS, DIVE_LAT, DIVE_LANG )
VALUES ('D'||LPAD(to_char(SEQ_DIVE_NO.NEXTVAL), 6, '0'),'WA00003' ,'DiveName3', 'Beautifull Place',
null,'0', '125.0215648', '25.5646846');

INSERT INTO DIVE (DIVE_NO, WEATHER_AREA_NO, DIVE_NAME, DIVE_DES, DIVE_IMG, DIVE_STATUS, DIVE_LAT, DIVE_LANG )
VALUES ('D'||LPAD(to_char(SEQ_DIVE_NO.NEXTVAL), 6, '0'),'WA00004' ,'DiveName4', 'Beautifull Place',
null,'0', '125.0215648', '25.5646846');

INSERT INTO DIVE (DIVE_NO, WEATHER_AREA_NO, DIVE_NAME, DIVE_DES, DIVE_IMG, DIVE_STATUS, DIVE_LAT, DIVE_LANG )
VALUES ('D'||LPAD(to_char(SEQ_DIVE_NO.NEXTVAL), 6, '0'),'WA00005' ,'DiveName5', 'Beautifull Place',null,'0', '125.0215648', '25.5646846');

//會員假資料
INSERT INTO MEM (MEM_NO,MEM_NAME,MEM_ID,MEM_PSW,MEM_GENERAL_GEN,MEM_GENERAL_BD,
MEM_TEL,MEM_EMAIL,MEM_ADD,MEM_PER,MEM_TYPE)
VALUES ('M'||LPAD(to_char(SEQ_MEM_NO.nextval),6,'0'),'魯夫','LUFY','123456','0',
to_date('1995-05-05','yyyy-mm-dd'),'0900123456','LUFY@gmail.com','中壢區中央路232巷50號',
'0','0');

INSERT INTO MEM (MEM_NO,MEM_NAME,MEM_ID,MEM_PSW,MEM_GENERAL_GEN,MEM_GENERAL_BD,
MEM_TEL,MEM_EMAIL,MEM_ADD,MEM_PER,MEM_TYPE)
VALUES ('M'||LPAD(to_char(SEQ_MEM_NO.nextval),6,'0'),'索隆','Zoro','123456','0',
to_date('1995-11-11','yyyy-mm-dd'),'0900123456','Zoro@gmail.com','中壢區中央路232巷50號',
'0','0');

INSERT INTO MEM (MEM_NO,MEM_NAME,MEM_ID,MEM_PSW,MEM_GENERAL_GEN,MEM_GENERAL_BD,
MEM_TEL,MEM_EMAIL,MEM_ADD,MEM_PER,MEM_TYPE)
VALUES ('M'||LPAD(to_char(SEQ_MEM_NO.nextval),6,'0'),'烏索普','Usopp','123456','0',
to_date('1995-04-01','yyyy-mm-dd'),'0900123456','Usopp@gmail.com','中壢區中央路232巷50號',
'0','0');

INSERT INTO MEM (MEM_NO,MEM_NAME,MEM_ID,MEM_PSW,MEM_GENERAL_GEN,MEM_GENERAL_BD,
MEM_TEL,MEM_EMAIL,MEM_ADD,MEM_PER,MEM_TYPE)
VALUES ('M'||LPAD(to_char(SEQ_MEM_NO.nextval),6,'0'),'艾斯','Ace','123456','0',
to_date('1995-01-01','yyyy-mm-dd'),'0900123456','Ace@gmail.com','中壢區中央路232巷50號',
'0','0');

INSERT INTO MEM (MEM_NO,MEM_NAME,MEM_ID,MEM_PSW,MEM_GENERAL_GEN,MEM_GENERAL_BD,
MEM_TEL,MEM_EMAIL,MEM_ADD,MEM_PER,MEM_TYPE)
VALUES ('M'||LPAD(to_char(SEQ_MEM_NO.nextval),6,'0'),'喬巴','Chopper','123456','0',
to_date('1995-12-24','yyyy-mm-dd'),'0900123456','Chopper@gmail.com','中壢區中央路232巷50號',
'0','0');

INSERT INTO MEM (MEM_NO,MEM_NAME,MEM_ID,MEM_PSW,MEM_GENERAL_GEN,MEM_GENERAL_BD,
MEM_TEL,MEM_EMAIL,MEM_ADD,MEM_PER,MEM_TYPE)
VALUES ('M'||LPAD(to_char(SEQ_MEM_NO.nextval),6,'0'),'羅賓','Robin','123456','1',
to_date('1995-02-06','yyyy-mm-dd'),'0900123456','Robin@gmail.com','中壢區中央路232巷50號',
'0','0');

INSERT INTO MEM (MEM_NO,MEM_NAME,MEM_ID,MEM_PSW,MEM_TEL,MEM_EMAIL,MEM_ADD,MEM_PER,MEM_TYPE,MEM_STORE_OWNER,MEM_STORE_TAXID)
VALUES ('M'||LPAD(to_char(SEQ_MEM_NO.nextval),6,'0'),'芒果潛水店','mango','123456',
'0900123456','Robin@gmail.com','中壢區中央路232巷50號','0','1','芒果','12345678');

INSERT INTO MEM (MEM_NO,MEM_NAME,MEM_ID,MEM_PSW,MEM_TEL,MEM_EMAIL,MEM_ADD,MEM_PER,MEM_TYPE,MEM_STORE_OWNER,MEM_STORE_TAXID)
VALUES ('M'||LPAD(to_char(SEQ_MEM_NO.nextval),6,'0'),'芭樂潛水店','mango','123456',
'0900123456','Robin@gmail.com','中壢區中央路232巷50號','0','1','芭樂','12345678');

INSERT INTO MEM (MEM_NO,MEM_NAME,MEM_ID,MEM_PSW,MEM_TEL,MEM_EMAIL,MEM_ADD,MEM_PER,MEM_TYPE,MEM_STORE_OWNER,MEM_STORE_TAXID)
VALUES ('M'||LPAD(to_char(SEQ_MEM_NO.nextval),6,'0'),'西瓜潛水店','mango','123456',
'0900123456','Robin@gmail.com','中壢區中央路232巷50號','0','1','西瓜','12345678');

INSERT INTO MEM (MEM_NO,MEM_NAME,MEM_ID,MEM_PSW,MEM_TEL,MEM_EMAIL,MEM_ADD,MEM_PER,MEM_TYPE,MEM_STORE_OWNER,MEM_STORE_TAXID)
VALUES ('M'||LPAD(to_char(SEQ_MEM_NO.nextval),6,'0'),'葡萄潛水店','mango','123456',
'0900123456','Robin@gmail.com','中壢區中央路232巷50號','0','1','葡萄','12345678');



//DIVEMESSAGE假資料
INSERT INTO DIVEMESSAGE (DIVMEG_NO , DIVE_NO  , MEM_NO  , DIVMEG_TIME  , DIVMEG_NOTE )
VALUES ('DM'||LPAD(to_char(SEQ_DIVEMESSAGEL_NO.NEXTVAL), 5, '0'),'D000001' ,'M000001', '2008-08-15 18:24:31','FHISFHIUSEHIFHESGIGHAIHAWEGHLAEWGWGH');

INSERT INTO DIVEMESSAGE (DIVMEG_NO , DIVE_NO  , MEM_NO  , DIVMEG_TIME  , DIVMEG_NOTE )
VALUES ('DM'||LPAD(to_char(SEQ_DIVEMESSAGEL_NO.NEXTVAL), 5, '0'),'D000002' ,'M000001', '2008-08-15 18:24:31','FHISFHIUSEHIFHESGIGHAIHAWEGHLAEWGWGH');

INSERT INTO DIVEMESSAGE (DIVMEG_NO , DIVE_NO  , MEM_NO  , DIVMEG_TIME  , DIVMEG_NOTE )
VALUES ('DM'||LPAD(to_char(SEQ_DIVEMESSAGEL_NO.NEXTVAL), 5, '0'),'D000003' ,'M000001', '2008-08-15 18:24:31','FHISFHIUSEHIFHESGIGHAIHAWEGHLAEWGWGH');

INSERT INTO DIVEMESSAGE (DIVMEG_NO , DIVE_NO  , MEM_NO  , DIVMEG_TIME  , DIVMEG_NOTE )
VALUES ('DM'||LPAD(to_char(SEQ_DIVEMESSAGEL_NO.NEXTVAL), 5, '0'),'D000004' ,'M000001', '2008-08-15 18:24:31','FHISFHIUSEHIFHESGIGHAIHAWEGHLAEWGWGH');




